Christian Sutton   
9/13/2020  

# Problem 1
**At a high-level, without entering into mathematical details, compare and contrast the following classifiers:**  
**Perceptron (textbook's version)-** The perceptron uses the perceptron update rule to minimize the classification error. While this seems like a good metric to use, it can over fit the training data and lead to bad generalization.  The classes for the perceptron must be linearly separable for the algorithm to converge, otherwise it will continue to run forever. The perceptron, like SVM, are built to handle numerical data that is normalized.  

**SVM-** The optimization problem solved in SVM is the maximization of the margin between classes which leads to better generalization to new data points versus the perception’s minimization of classification error. Also like the perceptron, the data must be linearly separable for the SVM algorithm to find a maximum margin between classes. Both the SVM and perceptron are built to handle numerical data that is normalized.  

**Decision Tree-** The Decision tree algorithm is very powerful but its power leads to problems of overfitting training data. Methods like tree pruning or averaging their output via an ensemble method, such as Random forest, is used to produce a better generalizable fit to the training data. The decision tree classifier can ingest numerical or categorial data and does not require data normalization such as the perceptron or SVM does. Training an optimal decision tree is known to be NP-complete.  

**Random Forest (you have to research a bit about this classifier)** Random forest is used to produce better generalized performance on new data versus a simple decision tree. Using this ensemble method, hyperparameter tuning becomes less critical for good performance. There is a balance with the number of decision trees used in the ensemble. If more tree are used, there is better performance against noise from the individual trees, however, this leads to increased computation cost. Like decision trees, this algorithm does not need data to be normalized and can also consume categorical as well as numerical data. 



# Problem 2

**Using real datasets (can also be hypothetically constructed by yourself) define the
following feature types, and give example values from your dataset. How would you represent
these features in a computer program? (e.g. 32-bit integer? Floating point? String?)**  
**Numerical-** For numerical data such as the Iris dataset, I would use and keep the float64 data type  
**Nominal-** For features that contain nominal data, if they are ordinal by nature, I would simply convert them to integers via SKlearn ordinal encoder. However, if the data in not ordinal by nature, one hot encoding via sklearn. the data type would be float64   
**Date-** For date data, I would convert to integer data like excel or possibly use a binning process. Date data, in my opinion can be thought processed similar to ordinal nominal data. The used data type would be float64.   
**Text-** for text data I would have to preprocess the features containing text and map them to 
**Image-** for image data, I would process the image into individual pixels such as has been done for datasets.digits  
**Dependent variable-**  


In [1]:

# Import datasets, classifiers and performance metrics
from sklearn import datasets, preprocessing
import pandas as pd
import numpy as np

# Numerical data

In [2]:
#I would just keep the data as is
iris1= datasets.load_iris()
iris1.data[0,:]

array([5.1, 3.5, 1.4, 0.2])

In [3]:
iris1.data[0,:].dtype

dtype('float64')

# Nominal Data

In [4]:
# preprocess data by creating int values
pets = ['dog', 'cat']
locationsBought = ['from Delaware', 'from Maryland']
enc = preprocessing.OneHotEncoder(categories=[pets, locationsBought])
X = [['dog', 'from Maryland'],['cat','from Delaware']]

In [5]:
enc.fit(X)

OneHotEncoder(categorical_features=None,
              categories=[['dog', 'cat'], ['from Delaware', 'from Maryland']],
              drop=None, dtype=<class 'numpy.float64'>, handle_unknown='error',
              n_values=None, sparse=True)

In [6]:
enc.transform([['dog', 'from Delaware']]).toarray()

array([[1., 0., 1., 0.]])

# Date data

In [7]:
# In this case I want to map date for this current week to ints. I'm just going to consider them as ordinal categories
enc1 = preprocessing.OrdinalEncoder()
X1 = [['9/13/20'], ['9/14/20'],['9/15/20'],['9/16/20'],['9/17/20'],['9/18/20'],['9/19/20']]
enc1.fit(X1)
enc1.transform([['9/15/20']])

array([[2.]])

# Text Data

In [8]:
# For text data, I need a preprocessor to handle the txt and map it back to a frequecy of occurence. (example used from sklearn) 
categories = ['sci.med']
from sklearn.datasets import fetch_20newsgroups
twenty_train = fetch_20newsgroups(subset='train',
    categories=categories, shuffle=True, random_state=42)

In [9]:
#example text

print("\n".join(twenty_train.data[0].split("\n")[:3]))

From: nyeda@cnsvax.uwec.edu (David Nye)
Subject: Re: Post Polio Syndrome Information Needed Please !!!
Organization: University of Wisconsin Eau Claire


In [10]:
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer()
X_train_counts = count_vect.fit_transform(twenty_train.data)
X_train_counts.shape

(594, 16257)

In [11]:
 from sklearn.feature_extraction.text import TfidfTransformer
tf_transformer = TfidfTransformer(use_idf=False).fit(X_train_counts)
X_train_tf = tf_transformer.transform(X_train_counts)
X_train_tf.shape


(594, 16257)

In [12]:
# now X_train data is of the form of a sparse matrix of float64
X_train_tf

<594x16257 sparse matrix of type '<class 'numpy.float64'>'
	with 99006 stored elements in Compressed Sparse Row format>

# Image data

In [13]:
#as stated above I would just process the images into pixles of float64 datatype
#this reflects the same thing as the dataset.load_digits 
from sklearn import datasets
d = datasets.load_digits()

In [14]:
d.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

# Problem 3

**Using online resources, research and find other classifier performance metrics**
**which are also as common as the accuracy metric. Write down the mathematical equations** 
**and the meaning of the metrics that you found**   
Researching online the main metrics I have found are:  
**Precision-**  Precision = (TruePositive)/(TruePositive+FalsePositive) Is a measure that tells the cusomer, of the predicted positives, how many are actually true.  
**Recall-**  Recall = (TruePositive)/(TruePositive+FalseNegative) Is a measure that tells the customer, of the predicted positives, how many positives were missed.  
**F1 Score-** 2 x (precision * Recall)/(precision + Recall) is a measure that tracks both good precision and good recall.    



# Problem 4

In [15]:
Admin =pd.read_csv("C:/Users/physi/Desktop/AppliedMachineLearning_EN.705.601/datasets_14872_228180_Admission_Predict.CSV")

In [16]:
Admin.head()

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0           1        337          118                  4  4.5   4.5  9.65   
1           2        324          107                  4  4.0   4.5  8.87   
2           3        316          104                  3  3.0   3.5  8.00   
3           4        322          110                  3  3.5   2.5  8.67   
4           5        314          103                  2  2.0   3.0  8.21   

   Research  Chance of Admit   
0         1              0.92  
1         1              0.76  
2         1              0.72  
3         1              0.80  
4         0              0.65

In [17]:
gradData= Admin.drop('Serial No.',axis= 1)

In [18]:
gradData.head()

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research  \
0        337          118                  4  4.5   4.5  9.65         1   
1        324          107                  4  4.0   4.5  8.87         1   
2        316          104                  3  3.0   3.5  8.00         1   
3        322          110                  3  3.5   2.5  8.67         1   
4        314          103                  2  2.0   3.0  8.21         0   

   Chance of Admit   
0              0.92  
1              0.76  
2              0.72  
3              0.80  
4              0.65

In [19]:
#covariance matrix - this will be overwritten into a correlation matrix after it is processed
corrMatrix= gradData.cov()

In [20]:
#standardDeviation of each feature in the original data

a1=gradData.iloc[:,0].std()
a2=gradData.iloc[:,1].std()
a3=gradData.iloc[:,2].std()
a4=gradData.iloc[:,3].std()
a5=gradData.iloc[:,4].std()
a6=gradData.iloc[:,5].std()
a7=gradData.iloc[:,6].std()
a8=gradData.iloc[:,7].std()

In [21]:
# overwrite covariance matrix by dividing by standard deviation (x)(y) at each cell
for i in range(0,8):
    for j in range(0,8):
        corrMatrix.iloc[i,j]=corrMatrix.iloc[i,j]/(eval("a"+str(i+1))*eval("a"+str(j+1)))
        
    

In [22]:
# This is now a correlation matrix
corrMatrix

GRE Score  TOEFL Score  University Rating       SOP  \
GRE Score           1.000000     0.835977           0.668976  0.612831   
TOEFL Score         0.835977     1.000000           0.695590  0.657981   
University Rating   0.668976     0.695590           1.000000  0.734523   
SOP                 0.612831     0.657981           0.734523  1.000000   
LOR                 0.557555     0.567721           0.660123  0.729593   
CGPA                0.833060     0.828417           0.746479  0.718144   
Research            0.580391     0.489858           0.447783  0.444029   
Chance of Admit     0.802610     0.791594           0.711250  0.675732   

                       LOR       CGPA  Research  Chance of Admit   
GRE Score          0.557555  0.833060  0.580391          0.802610  
TOEFL Score        0.567721  0.828417  0.489858          0.791594  
University Rating  0.660123  0.746479  0.447783          0.711250  
SOP                0.729593  0.718144  0.444029          0.675732  
LOR                1.000000  0.670211  0.396859          0.669889  
CGPA               0.670211  1.000000  0.521654          0.873289  
Research           0.396859  0.521654  1.000000          0.553202  
Chance of Admit    0.669889  0.873289  0.553202          1.000000

In [23]:
# this is a match to the above
# each feature is always correlated to itself; that is why all the diagonal elements are equal to 1
#seems CGPA, GRE, TOEFL are strongly correlated to chance of admit


gradData.corr()

GRE Score  TOEFL Score  University Rating       SOP  \
GRE Score           1.000000     0.835977           0.668976  0.612831   
TOEFL Score         0.835977     1.000000           0.695590  0.657981   
University Rating   0.668976     0.695590           1.000000  0.734523   
SOP                 0.612831     0.657981           0.734523  1.000000   
LOR                 0.557555     0.567721           0.660123  0.729593   
CGPA                0.833060     0.828417           0.746479  0.718144   
Research            0.580391     0.489858           0.447783  0.444029   
Chance of Admit     0.802610     0.791594           0.711250  0.675732   

                       LOR       CGPA  Research  Chance of Admit   
GRE Score          0.557555  0.833060  0.580391          0.802610  
TOEFL Score        0.567721  0.828417  0.489858          0.791594  
University Rating  0.660123  0.746479  0.447783          0.711250  
SOP                0.729593  0.718144  0.444029          0.675732  
LOR                1.000000  0.670211  0.396859          0.669889  
CGPA               0.670211  1.000000  0.521654          0.873289  
Research           0.396859  0.521654  1.000000          0.553202  
Chance of Admit    0.669889  0.873289  0.553202          1.000000