# problem 1
**[50 pts] In this assignment, we will use Apriori analysis to find noun phrases, or interesting patterns in a novel.**  



In [1]:
# create csv file of Alice txt
import pandas as pd
import nltk
import re
from nltk.corpus import gutenberg, stopwords
# # nltk.download('stopwords')
# # nltk.download('gutenberg')
# # nltk.download('punkt')
# Stop_words = stopwords.words('english')
# Sentences = gutenberg.sents('carroll-alice.txt')
# TermsSentences = []
# for terms in Sentences:
#     terms = [w for w in terms if w not in Stop_words]
#     terms = [w for w in terms if re.search(r'^[a-zA-Z]{2}', w) is not None]
#     TermsSentences+= [terms]

In [2]:
#Store file for module 10
# pd.DataFrame(TermsSentences).to_csv("C:/Users/physi/Desktop/AppliedMachineLearning_EN.705.601/Mod11/AliceTxt.csv", index=False)


In [3]:
#normalize data using module 10
from collections import defaultdict
import csv
from itertools import combinations 
import numpy as np

Transactions_list = []  # a list of transactions
Items_names = {}  # Lookup item ID to name
Items_ids = {}  # Lookup item name to ID

Items = None  # a list of item IDs, normally an increasing sequence of numbers

# Process the data
with open('C:/Users/physi/Desktop/AppliedMachineLearning_EN.705.601/Mod11/AliceTxt.csv', 'r') as fin:
    reader = csv.reader(fin, delimiter=',')
    item_id = 0
    for row in reader:
        transaction = []
        for item in row:
            if item not in Items_ids:
                Items_ids[item] = item_id
                Items_names[item_id] = item
                item_id += 1
            #
            transaction += [Items_ids[item]]
        #
        Transactions_list += [transaction]

M, N = len(Items_ids), len(Transactions_list)

Items = np.arange(0,M)

# Information
print(f'M={M} items, N={N} transactions')

M=2793 items, N=1703 transactions


In [4]:
# check data
print([Items_names[_] for _ in Items[0:7]])
print(Transactions_list[:300])

['Alice', 'Adventures', 'Wonderland', 'Lewis', 'Carroll', 'CHAPTER', 'Down']
[[0, 1, 2, 3, 4], [5], [6, 7, 8], [0, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 13, 19, 20, 21, 22, 18, 23, 0, 24, 20, 25], [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 7, 50, 51, 52, 53], [54, 15, 55, 56, 0, 57, 55, 58, 59, 60, 7, 61, 62, 63], [62, 63], [64, 65], [23, 66, 67, 68, 69, 70, 71, 72, 73, 7, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 0, 84, 85, 86, 87, 28, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 52, 87, 98, 99, 70, 100, 101, 102, 90, 103, 104], [105, 106, 107, 108, 0, 88, 27, 109, 10], [110, 90, 103, 108, 111, 112, 113, 59, 114, 48, 48, 0, 107, 57, 115, 116, 117, 118, 29], [119, 29, 118, 120, 121, 122, 70, 108, 123, 124, 125, 126, 127], [128, 129, 123, 130, 131, 132, 100, 133, 82, 134, 29, 135, 136, 137, 18, 138, 139, 140, 20, 141, 142, 143], [144, 145, 146, 147, 138, 148, 149, 150, 151, 152, 153, 154, 112, 155, 146, 156, 157, 158, 159, 160, 147, 137, 1

In [5]:
# Convert to numpy arrays
Transactions = np.full((N,M), False, dtype=np.bool)

for i, t in enumerate(Transactions_list):
    for item in t:
        Transactions[i][item] = True

# Sanity, print row index 10, 11
print(f'{Transactions[10:12].astype(int)}')

[[1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [6]:
# process data for Weka 
# Filename = 'C:/Users/physi/Desktop/AppliedMachineLearning_EN.705.601/Mod11/AliceTxt_weka.csv'

# with open(Filename, 'w',newline="") as fout:
#     writer = csv.writer(fout, delimiter=',', quoting=csv.QUOTE_ALL, quotechar="'", lineterminator='\n')
#     writer.writerow([Items_names[i] for i in range(M)])
#     for i in range(N):
#         writer.writerow(list(map(lambda x: '' if x == False else 'True',  Transactions[i])))

# Problem 2

**2. [50 pts] The module class NeuralNetMLP is a single hidden layer neural network implementation. Make the necessary modifications to upgrade it to a 2 hidden layer network. Run it on the MNIST dataset and report its performance.**



In [7]:
%matplotlib inline
import matplotlib.pyplot as plt

from numpy import array, full, concatenate
from numpy.random import ranf


In [8]:
def load_mnist(path, kind='train'):
    from numpy import fromfile, uint8
    import os
    import struct
    
    labels_path = os.path.join(path, '%s-labels.idx1-ubyte' % kind)
    images_path = os.path.join(path, '%s-images.idx3-ubyte' % kind)
    with open(labels_path, 'rb') as lbpath:
        magic, n = struct.unpack('>II', lbpath.read(8))
        labels = fromfile(lbpath, dtype=uint8)
        with open(images_path, 'rb') as imgpath:
            magic, num, rows, cols = struct.unpack(">IIII",imgpath.read(16))
            images = fromfile(imgpath, dtype=uint8).reshape(len(labels), 784)
            images = ((images / 255.) - .5) * 2
    #
    return images, labels

X_train, y_train = load_mnist('C:/Users/physi/Desktop/AppliedMachineLearning_EN.705.601/Mod11/', kind='train')
print(f'Rows= {X_train.shape[0]}, columns= {X_train.shape[1]}')

X_test, y_test = load_mnist('C:/Users/physi/Desktop/AppliedMachineLearning_EN.705.601/Mod11/', kind='t10k')
print(f'Rows= {X_test.shape[0]}, columns= {X_test.shape[1]}')

Rows= 60000, columns= 784
Rows= 10000, columns= 784


In [9]:
from numpy import random, zeros, exp, clip, dot, log, sum, argmax, unique, arange, float
    
class NeuralNetMLP(object):
    def __init__(self, n_hidden=30, epochs=100, eta=0.001, minibatch_size=1, seed=None):
        self.random = random.RandomState(seed)  # used to randomize weights
        
        # add hidden layer variable 
        
        self.n_hidden = n_hidden  # size of the hidden layer
        self.epochs = epochs  # number of iterations
        self.eta = eta  # learning rate
        self.minibatch_size = minibatch_size  # size of training batch - 1 would not work
    
    @staticmethod
    def onehot(y, n_classes):  # one hot encode the input class y
        onehot = zeros((n_classes, y.shape[0]))
        for idx, val in enumerate(y.astype(int)):
            onehot[val, idx] = 1.0
        return onehot.T
    
    @staticmethod
    def sigmoid(z):  # Eq 1
        return 1.0 / (1.0 + exp(-clip(z, -250, 250)))

    def _forward(self, X):  # Eq 2
        z_h = dot(X, self.w_h)
        a_h = self.sigmoid(z_h)
        
        #add hidden layer
        z_h2 = dot(a_h, self.w_h2) # made correction here a_h2-> a_h
        a_h2 = self.sigmoid(z_h2)
        
        z_out = dot(a_h2, self.w_out)# made correction here z_h->z_h2
        a_out = self.sigmoid(z_out)
        
        #add hidden layer variables z_h2, a_h2
        return z_h, a_h, z_h2, a_h2, z_out, a_out 

    @staticmethod
    def compute_cost(y_enc, output):  # Eq 4
        term1 = -y_enc * (log(output))
        term2 = (1.0-y_enc) * log(1.0-output)
        cost = sum(term1 - term2)
        return cost

    def predict(self, X):
        z_h, a_h, z_h2, a_h2, z_out, a_out = self._forward(X)
        y_pred = argmax(z_out, axis=1)
        return y_pred

    def fit(self, X_train, y_train, X_valid, y_valid):
        import sys
        n_output = unique(y_train).shape[0]  # number of class labels
        n_features = X_train.shape[1]
        self.w_out = self.random.normal(loc=0.0, scale=0.1, size=(self.n_hidden, n_output))
        self.w_h = self.random.normal(loc=0.0, scale=0.1, size=(n_features, self.n_hidden))
        
        # add hidden layer - same size as previous hidden layer
        self.w_h2 = self .random.normal(loc=0.0,scale=0.1, size=(self.n_hidden, self.n_hidden))
        
        y_train_enc = self.onehot(y_train, n_output)  # one-hot encode original y
        for i in range(self.epochs):
            indices = arange(X_train.shape[0])
            for start_idx in range(0, indices.shape[0] - self.minibatch_size + 1, self.minibatch_size):
                batch_idx = indices[start_idx:start_idx + self.minibatch_size]
                
                # report forward with new second hidden layer output
                z_h, a_h, z_h2, a_h2, z_out, a_out = self._forward(X_train[batch_idx])
                
                #add delta_h2
                sigmoid_derivative_h = a_h * (1.0-a_h)  # Eq 3
                sigmoid_derivative_h2 = a_h2 * (1.0-a_h2)  # Eq 3
                delta_out = a_out - y_train_enc[batch_idx]  # Eq 5
                 #add
                delta_h2 = (dot(delta_out, self.w_out.T) * sigmoid_derivative_h2)  # Eq 6) 
                delta_h = (dot(delta_h2, self.w_h2.T) * sigmoid_derivative_h)  # Eq 6 
                
                
                #add grad w_h2
                grad_w_out = dot(a_h2.T, delta_out)  # Eq 7
                #add
                grad_w_h2 = dot(a_h.T, delta_h2)
                grad_w_h = dot(X_train[batch_idx].T, delta_h)  # Eq 8
               
                
                #add W.h2
                self.w_out -= self.eta*grad_w_out  # Eq 9
                self.w_h -= self.eta*grad_w_h  # Eq 9
                #add 
                self.w_h2 -= self.eta*grad_w_h2
                
            # Evaluation after each epoch during training
            z_h, a_h, z_h2, a_h2, z_out, a_out = self._forward(X_train)
            cost = self.compute_cost(y_enc=y_train_enc, output=a_out)
            y_train_pred = self.predict(X_train)  # monitoring training progress through reclassification
            y_valid_pred = self.predict(X_valid)  # monitoring training progress through validation
            train_acc = ((sum(y_train == y_train_pred)).astype(float) / X_train.shape[0])
            valid_acc = ((sum(y_valid == y_valid_pred)).astype(float) / X_valid.shape[0])
            sys.stderr.write('\r%d/%d | Cost: %.2f ' '| Train/Valid Acc.: %.2f%%/%.2f%% '%
                (i+1, self.epochs, cost, train_acc*100, valid_acc*100))
            sys.stderr.flush()
        #
        return self

In [10]:
nn = NeuralNetMLP(n_hidden=20, epochs=300, eta=0.0005, minibatch_size=100, seed=1)

nn.fit(X_train=X_train[:55000], y_train=y_train[:55000], X_valid=X_train[55000:], y_valid=y_train[55000:]) ;

# at n_hidden=20, epochs=300, eta=0.0005, minibatch_size=100, seed=1
# 300/300 | Cost: 7849.39 | Train/Valid Acc.: 98.05%/95.74%  

300/300 | Cost: 7849.39 | Train/Valid Acc.: 98.05%/95.74%  

In [11]:
from sklearn.metrics import confusion_matrix
y_pred = nn.predict(X_test)
test_acc = ((sum(y_test == y_pred)).astype(float) / y_test.shape[0])

print(f'Accuracy= {test_acc*100:.2f}%')
print(confusion_matrix(y_test,y_pred))

Accuracy= 94.82%
[[ 957    0    1    1    0    3    7    3    6    2]
 [   0 1106    7    1    0    1    3    3   14    0]
 [  10    2  971   11    5    0    3    9   21    0]
 [   0    1   18  954    0   13    0   11   10    3]
 [   2    0    4    2  936    0    7    5    1   25]
 [   8    1    1   29    3  820   11    3   11    5]
 [   9    3    6    0   10   10  918    0    2    0]
 [   1    5   11   14   11    0    0  976    2    8]
 [   5    2    6   16    6    7    5    7  913    7]
 [   5    4    1   14   36    1    1   10    6  931]]
